addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: d7e02587-9aee-444e-8aa8-257996e2d331
after_success: [./df-build.sh]
language: java
# Modified by Insights Service at 2016-03-04 11:51:07.612125
